name = "galactic-canvas-dev-api"
main = "src/index.ts"

compatibility_date = "2025-02-20"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

routes = [
  { pattern = "canvas.neontowel.dev/api/*", zone_name = "neontowel.dev" }
]
